# Generated by Django 5.1.15 on 2026-10-02 15:34

import apps.obligations.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('regulatoria', 'Regulatoria'), ('contractual', 'Contractual'), ('interna', 'Interna')], default='regulatoria', max_length=20)),
                ('periodicity', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unica', 'Única')], default='anual', max_length=20)),
                ('legal_basis', models.TextField(blank=True)),
                ('legal_basis_url', models.URLField(blank=True, max_length=500)),
                ('expected_evidence', models.CharField(max_length=255)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('due_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('due_time', models.TimeField(default=datetime.time(17, 0))),
                ('default_priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='organizations.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='organizations.company')),
                ('control_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='organizations.controlentity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_obligations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'obligación',
                'verbose_name_plural': 'obligaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('preparation_date', models.DateField()),
                ('due_at', models.DateTimeField(db_index=True)),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stage', models.CharField(choices=[('sin_iniciar', 'Sin iniciar'), ('en_preparacion', 'En preparación'), ('pendiente_validacion', 'Pendiente de validación')], default='sin_iniciar', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_suspended', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_periods', to=settings.AUTH_USER_MODEL)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_periods', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='organizations.company')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='obligations.obligation')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_periods', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_periods', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_periods', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'período',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=300, upload_to=apps.obligations.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('valido', 'Válido'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado')], default='valido', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='obligations.period')),
            ],
            options={
                'verbose_name': 'documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('previous_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_events', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='obligations.period')),
            ],
            options={
                'verbose_name': 'evento de período',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='obligation',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_obligation_company_name'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['company', 'is_closed', 'due_at'], name='obligations_company_710c14_idx'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('obligation', 'label'), name='uniq_period_label'),
        ),
    ]
