# Generated by Django 5.1.15 on 2026-10-02 15:34

import apps.reminders.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('vencimiento', 'Día del vencimiento'), ('escalamiento', 'Escalamiento'), ('manual', 'Reenvío manual')], max_length=20)),
                ('offset_days', models.SmallIntegerField(blank=True, null=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('scheduled_for', models.DateField(help_text='Fecha local de la empresa en que correspondía el aviso.')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('reintentado', 'Reintentado')], max_length=15)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='obligations.period')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='reminders.notification')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offsets', models.JSONField(default=apps.reminders.models.default_offsets)),
                ('send_time', models.TimeField(default=datetime.time(8, 0))),
                ('copy_backup', models.BooleanField(default=True)),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalation_days', models.PositiveSmallIntegerField(default=2)),
                ('escalation_repeat_days', models.PositiveSmallIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to='organizations.company')),
            ],
            options={
                'verbose_name': 'configuración de recordatorios',
                'verbose_name_plural': 'configuraciones de recordatorios',
            },
        ),
    ]
