# Generated by Django 5.1.15 on 2026-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('module', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=64)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('failure', 'Fallido')], default='success', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
