# Generated by Django 5.1.15 on 2026-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Skelleton Base', max_length=150)),
                ('short_name', models.CharField(default='Skelleton', max_length=50)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='', max_length=500)),
                ('color_primary', models.CharField(default='#0D6EFD', max_length=7)),
                ('color_secondary', models.CharField(default='#000000', max_length=7)),
                ('color_background', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_headings', models.CharField(default='#000000', max_length=7)),
                ('color_text', models.CharField(default='#000000', max_length=7)),
                ('color_links', models.CharField(default='#0D6EFD', max_length=7)),
                ('color_buttons', models.CharField(default='#0D6EFD', max_length=7)),
                ('color_menu', models.CharField(default='#000000', max_length=7)),
                ('font_primary', models.CharField(default='system-ui', max_length=50)),
                ('font_secondary', models.CharField(default='system-ui', max_length=50)),
                ('font_size_base', models.PositiveSmallIntegerField(default=16)),
                ('border_radius', models.CharField(default='md', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
