# Generated by Django 5.1.15 on 2026-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_seed_default_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='short_name',
            field=models.CharField(default='Matriz', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='site_name',
            field=models.CharField(default='Matriz Administrativa de Obligaciones', max_length=150),
        ),
    ]
