# Generated by Django 5.1.15 on 2026-10-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('usuarios.ver', 'Ver usuarios'), ('usuarios.crear', 'Crear usuarios'), ('usuarios.editar', 'Editar usuarios y su asignación de roles/permisos'), ('usuarios.deshabilitar', 'Habilitar, deshabilitar, bloquear y desbloquear usuarios'), ('usuarios.restablecer_password', 'Enviar enlace de restablecimiento, forzar cambio de contraseña en el próximo inicio o cerrar sesiones activas de un usuario'), ('roles.ver', 'Ver roles y el catálogo de permisos'), ('roles.editar', 'Crear, editar y eliminar roles'), ('permisos.ver', 'Ver el catálogo de permisos y a qué módulo pertenece cada uno'), ('configuracion.ver', 'Ver configuración del sistema'), ('configuracion.editar', 'Editar configuración del sistema'), ('matriz.ver_todas', 'Ver todas las obligaciones de la empresa (sin este permiso, solo las propias: donde es responsable o suplente)'), ('matriz.crear', 'Crear obligaciones'), ('matriz.editar', 'Editar obligaciones y el seguimiento de los períodos'), ('matriz.cambiar_fecha', 'Cambiar la fecha de vencimiento (con justificación)'), ('matriz.cargar', 'Cargar evidencias y eliminar las rechazadas'), ('matriz.enviar', 'Enviar períodos a validación'), ('matriz.validar', 'Validar cierres, devolver períodos y rechazar evidencias'), ('matriz.recordar', 'Reenviar recordatorios y reintentar avisos fallidos'), ('matriz.exportar', 'Exportar la matriz y los reportes a Excel o PDF'), ('matriz.ver_auditoria', 'Ver el historial de auditoría y de notificaciones de la empresa'), ('matriz.configurar', 'Configurar la empresa y sus recordatorios'), ('matriz.gestionar_miembros', 'Asignar y quitar roles de personas en la empresa'), ('empresas.ver', 'Ver empresas y sucursales'), ('empresas.editar', 'Crear, editar y desactivar empresas y sucursales'), ('catalogos.ver', 'Ver áreas y entidades de control'), ('catalogos.editar', 'Crear, editar y eliminar áreas y entidades de control'), ('auditoria.ver', 'Ver el registro de auditoría'), ('auditoria.ver_detalle', 'Ver el detalle (valores anteriores y nuevos) de un evento'), ('auditoria.ver_ubicacion', 'Ver la ubicación aproximada asociada a un evento'), ('auditoria.exportar', 'Exportar el registro de auditoría')]},
        ),
    ]
