# Generated by Django 5.1.15 on 2026-10-02 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'área',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ControlEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'entidad de control',
                'verbose_name_plural': 'entidades de control',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=80)),
                ('country', models.CharField(default='Ecuador', max_length=80)),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='America/Guayaquil', max_length=64)),
                ('color', models.CharField(default='#164b86', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe tener el formato #RRGGBB.', regex='^#[0-9a-fA-F]{6}$')])),
                ('compliance_date_basis', models.CharField(choices=[('validation', 'Fecha de validación'), ('submission', 'Fecha de envío a validación')], default='validation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('general_manager', models.ForeignKey(blank=True, help_text='Aprobador por defecto de los períodos de la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.company')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_branch_company_name')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('administrador', 'Administrador'), ('responsable', 'Responsable'), ('supervisor', 'Supervisor/Aprobador'), ('auditor', 'Auditor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='memberships', to='organizations.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía',
                'ordering': ['company__short_name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='uniq_membership_user_company')],
            },
        ),
    ]
